import React, { useState } from "react";
import { ShieldCheck, Flame, Leaf, HelpCircle, Activity, Play, Zap, RotateCw } from "lucide-react";
import { StadiumSector } from "../types";
import { EMERGENCY_SCENARIOS } from "../utils/stadiumData";

interface OrganizerProps {
  sectors: StadiumSector[];
  announceText: (text: string) => void;
}

export const OrganizerSection: React.FC<OrganizerProps> = ({
  sectors,
  announceText,
}) => {
  // Emergency support states
  const [selectedScenarioId, setSelectedScenarioId] = useState(EMERGENCY_SCENARIOS[0].id);
  const [emergencyResult, setEmergencyResult] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  // Sustainability Metrics (Mock static counts with optional increment animations)
  const [wasteRecycled, setWasteRecycled] = useState(2450);
  const [energySaved, setEnergySaved] = useState(420);

  const handleGenerateEmergencyProtocol = async () => {
    const scenario = EMERGENCY_SCENARIOS.find((sc) => sc.id === selectedScenarioId);
    if (!scenario) return;

    setIsLoading(true);
    setEmergencyResult("");
    announceText("Emergency coordinator synthesizing action parameters.");

    try {
      const response = await fetch("/api/copilot/emergency", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          scenario: scenario.title + " - " + scenario.description,
          location: "Stadium Plazas and Concourse Zones",
          currentImpact: scenario.currentImpact,
        }),
      });

      const data = await response.json();
      if (response.ok && data.response) {
        setEmergencyResult(data.response);
        announceText(`Critical Action Matrix generated by AI for scenario: ${scenario.title}`);
      } else {
        throw new Error(data.error || "Emergency dispatch node failure");
      }
    } catch {
      // Local fallback emergency manual
      const fallbacks: Record<string, string> = {
        "scen-1": "Tactical Protocol [SUPPORTER BLOCKAGE]:\n• Dispatch crowd controllers to redirect Gate S2 lines.\n• Turn on East Plazas large digital display guides.\n• Issue push alerts urging Sector C fans to dwell or access food blocks.",
        "scen-2": "Tactical Protocol [LIGHTNING PROTOCOL]:\n• Broadcast evacuation sirens stadium-wide.\n• Open all interior concourse gate safety tunnels.\n• Deploy field crews to safely clear open plazas.",
        "scen-3": "Tactical Protocol [TRANSIT SHUTDOWN]:\n• Activate secondary fan dwell entertainment guides on giant screens.\n• Deploy emergency bus shuttles to Sector A plaza loop.\n• Broaden concession operational hours in North blocks."
      };
      setEmergencyResult(fallbacks[selectedScenarioId] || "Deploy tactical monitors immediately.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleRecyclePlastic = () => {
    setWasteRecycled((prev) => prev + 150);
    announceText("Spectator green sorting logged. Waste offset updated +150 kg.");
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
      {/* Crowd Density Comparison & Sustainability Overview */}
      <div className="lg:col-span-6 space-y-6">
        {/* Crowd Levels Sector Bar Chart */}
        <div className="bg-white dark:bg-zinc-900 rounded-xl p-5 border border-zinc-100 dark:border-zinc-800/80">
          <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2 mb-2">
            <Activity className="w-4 h-4 text-emerald-600" /> Sector Occupancy Monitor
          </h3>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-5">
            Real-time spectator densities across four primary stadium zones.
          </p>

          <div className="space-y-4">
            {sectors.map((sec) => (
              <div key={sec.id}>
                <div className="flex justify-between items-center text-xs mb-1">
                  <span className="font-semibold text-zinc-700 dark:text-zinc-300">
                    {sec.name.split(" - ")[0]}
                  </span>
                  <span className="font-bold text-zinc-900 dark:text-zinc-100">
                    {sec.crowdLevel}% Occupancy
                  </span>
                </div>
                <div className="w-full bg-zinc-100 dark:bg-zinc-800 h-2.5 rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-500 ${
                      sec.status === "critical" ? "bg-red-500" :
                      sec.status === "crowded" ? "bg-amber-500" :
                      "bg-emerald-500"
                    }`}
                    style={{ width: `${sec.crowdLevel}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Sustainability Dashboard */}
        <div className="bg-white dark:bg-zinc-900 rounded-xl p-5 border border-zinc-100 dark:border-zinc-800/80">
          <div className="flex justify-between items-center mb-2">
            <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <Leaf className="w-4 h-4 text-emerald-600" /> Sustainability & Offset Dashboard
            </h3>
            <button
              onClick={handleRecyclePlastic}
              id="btn-simulate-sorting"
              className="text-[10px] bg-emerald-50 text-emerald-700 border border-emerald-100 hover:bg-emerald-100 dark:bg-emerald-950/20 dark:text-emerald-400 dark:border-emerald-900/50 px-2 py-1 rounded font-bold transition-all"
            >
              Recycle +150kg
            </button>
          </div>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-4">
            Real-time tracking of green initiatives and public transportation offsets for the tournament.
          </p>

          <div className="grid grid-cols-2 gap-4">
            <div className="p-3.5 bg-zinc-50 dark:bg-zinc-800/50 rounded-xl border border-zinc-100 dark:border-zinc-800 flex items-center gap-3">
              <div className="p-2 bg-emerald-50 dark:bg-emerald-950/30 rounded-lg text-emerald-600 dark:text-emerald-400">
                <Leaf className="w-5 h-5" />
              </div>
              <div>
                <span className="text-[10px] text-zinc-400 uppercase font-bold block">Waste Diverted</span>
                <span className="text-sm font-bold text-zinc-800 dark:text-zinc-100">{wasteRecycled} kg</span>
              </div>
            </div>

            <div className="p-3.5 bg-zinc-50 dark:bg-zinc-800/50 rounded-xl border border-zinc-100 dark:border-zinc-800 flex items-center gap-3">
              <div className="p-2 bg-amber-50 dark:bg-amber-950/30 rounded-lg text-amber-600 dark:text-amber-400">
                <Zap className="w-5 h-5" />
              </div>
              <div>
                <span className="text-[10px] text-zinc-400 uppercase font-bold block">Energy Conserved</span>
                <span className="text-sm font-bold text-zinc-800 dark:text-zinc-100">{energySaved} kWh</span>
              </div>
            </div>
          </div>

          <div className="mt-4 p-3 bg-zinc-50/50 dark:bg-zinc-800/20 rounded-xl border border-zinc-100 dark:border-zinc-800 text-[11px] text-zinc-600 dark:text-zinc-400 flex items-center gap-2">
            <span>🚇</span>
            <span><strong>Public Transit Offset:</strong> 85% of fans accessed the stadium via light rail, removing an estimated 1,200 vehicles from roadways.</span>
          </div>
        </div>
      </div>

      {/* Emergency Decision Support Protocol */}
      <div className="lg:col-span-6 bg-white dark:bg-zinc-900 rounded-xl p-5 border border-zinc-100 dark:border-zinc-800/80 flex flex-col justify-between">
        <div>
          <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2 mb-2">
            <ShieldCheck className="w-4 h-4 text-emerald-600" /> Emergency Decision Support Terminal
          </h3>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-4">
            Simulate operational crises (lightning storms, train bottlenecks, supporters gate blocks) to generate immediate AI tactical response matrices.
          </p>

          <div className="space-y-4">
            <div>
              <label htmlFor="emergency-scenario-select" className="block text-[10px] font-bold text-zinc-500 dark:text-zinc-400 uppercase">Select Scenario Profile</label>
              <select
                id="emergency-scenario-select"
                value={selectedScenarioId}
                onChange={(e) => {
                  setSelectedScenarioId(e.target.value);
                  setEmergencyResult("");
                }}
                className="w-full mt-1 text-xs font-semibold bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-2.5 text-zinc-700 dark:text-zinc-300 outline-none cursor-pointer"
              >
                {EMERGENCY_SCENARIOS.map((scen) => (
                  <option key={scen.id} value={scen.id}>{scen.title}</option>
                ))}
              </select>
            </div>

            <div className="p-3 bg-zinc-50 dark:bg-zinc-800/40 rounded-lg border border-zinc-100 dark:border-zinc-800/80 text-xs text-zinc-600 dark:text-zinc-400">
              <strong>Simulated Impact:</strong> {EMERGENCY_SCENARIOS.find((sc) => sc.id === selectedScenarioId)?.currentImpact}
            </div>

            <button
              onClick={handleGenerateEmergencyProtocol}
              id="btn-generate-protocol"
              disabled={isLoading}
              className="w-full py-2 bg-red-600 hover:bg-red-500 text-white rounded-lg text-xs font-bold transition flex items-center justify-center gap-2 disabled:opacity-60"
            >
              {isLoading ? (
                <RotateCw className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Play className="w-3.5 h-3.5" />
              )}
              <span>{isLoading ? "Generating Critical Action Protocol..." : "Generate AI Critical Protocol Matrix"}</span>
            </button>

            {emergencyResult && (
              <div className="p-4 bg-red-50/50 dark:bg-red-950/20 border border-red-100 dark:border-red-900/30 rounded-xl space-y-1">
                <span className="text-[10px] font-bold text-red-800 dark:text-red-400 uppercase tracking-wider block">⚠️ AI Action Directive</span>
                <div className="text-xs text-zinc-800 dark:text-zinc-200 whitespace-pre-line leading-relaxed font-semibold">
                  {emergencyResult}
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="text-[10px] text-zinc-400 italic mt-6 pt-3 border-t border-zinc-100 dark:border-zinc-800">
          * Decoupled tactical models are designed for backup high-availability in case of cellular network outages.
        </div>
      </div>
    </div>
  );
};
